# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 103bff06b934006d2ef2a53ab9c44f4e10e388fd44ac4a45943d1a2b3d6a11509ea87acb0d7040fe452a711f0afad1d31e32463c4488c36416120f227c54857e

test:
  secret_key_base: b40f033344296112ce0be5bd55a2d115369378d48403d9043faf92ea5aff891b122a50b1ce19d2d0f78e2f76bd08c703ae12e1b0d7709c149e73f1eba1a4a548

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
